# -*- coding: utf-8 -*-
"""Azalea Calde.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1scbRKevYjNZgXjCde_FZQXDTBLIESKRU
"""

import pandas as pd
import numpy as np
from sklearn.metrics import cohen_kappa_score
from statsmodels.stats.inter_rater import fleiss_kappa

# 1. Caricamento del dataset
file_path = "/content/sample_data/Azalea-annotations_2025-02-11 (1).csv"
df = pd.read_csv(file_path)


# 2. Mappatura delle categorie in numeri
mapping_hs = {'yes': 1, 'no': 0}
mapping_irony = {'yes': 1, 'no': 0}
mapping_stance = {'favor': 2, 'none': 1, 'against': 0}  # Valori non negativi per il Fleiss' Kappa

df['hs'] = df['hs'].map(mapping_hs)
df['irony'] = df['irony'].map(mapping_irony)
df['stance'] = df['stance'].map(mapping_stance)

# 3. Divisione del dataset in base al profilo degli annotatori
df_high = df[df['profile'] == 'high']
df_low = df[df['profile'] == 'low']

# 4. Funzione per creare la matrice di conteggio per il Fleiss' Kappa
def create_fleiss_matrix(data, column, n_categories=3):
    """
    Raggruppa i dati per tweet e conta quante annotazioni ricadono in ciascuna categoria.
    n_categories: numero totale di categorie possibili.
    """
    # Raggruppa per 'tweet_id' e conta le occorrenze per ciascuna categoria
    grouped = data.groupby('tweet_id')[column].apply(
        lambda x: np.bincount(x.dropna().astype(int), minlength=n_categories)
    )
    return np.vstack(grouped.values)

# 5. Creazione delle matrici per il calcolo del Fleiss' Kappa
# (Notare che per 'hs' e 'irony' ci sono solo 2 categorie, ma usiamo minlength=3 per uniformità;
#  la terza colonna rimarrà sempre a zero.)
matrix_hs = create_fleiss_matrix(df, 'hs', n_categories=3)
matrix_stance = create_fleiss_matrix(df, 'stance', n_categories=3)
matrix_irony = create_fleiss_matrix(df, 'irony', n_categories=3)

# 6. Calcolo del Fleiss' Kappa per tutti gli annotatori
fleiss_hs = fleiss_kappa(matrix_hs)
fleiss_stance = fleiss_kappa(matrix_stance)
fleiss_irony = fleiss_kappa(matrix_irony)

# 7. Calcolo del Cohen's Kappa confrontando le annotazioni dei profili "high" e "low"
# Si assume che per ogni tweet esista una sola annotazione per ciascun profilo.
pivot = df.pivot_table(index='tweet_id', columns='profile', aggfunc='first')

kappa_hs = cohen_kappa_score(pivot[('hs', 'high')], pivot[('hs', 'low')])
kappa_stance = cohen_kappa_score(pivot[('stance', 'high')], pivot[('stance', 'low')])
kappa_irony = cohen_kappa_score(pivot[('irony', 'high')], pivot[('irony', 'low')])

# 8. Calcolo del Fleiss' Kappa per i sottogruppi (high e low)
fleiss_hs_high = fleiss_kappa(create_fleiss_matrix(df_high, 'hs'))
fleiss_stance_high = fleiss_kappa(create_fleiss_matrix(df_high, 'stance'))
fleiss_irony_high = fleiss_kappa(create_fleiss_matrix(df_high, 'irony'))

fleiss_hs_low = fleiss_kappa(create_fleiss_matrix(df_low, 'hs'))
fleiss_stance_low = fleiss_kappa(create_fleiss_matrix(df_low, 'stance'))
fleiss_irony_low = fleiss_kappa(create_fleiss_matrix(df_low, 'irony'))

# 9. Visualizzazione dei risultati
results = {
    "Cohen's Kappa - Hate Speech": kappa_hs,
    "Cohen's Kappa - Stance": kappa_stance,
    "Cohen's Kappa - Irony": kappa_irony,
    "Fleiss' Kappa - Hate Speech": fleiss_hs,
    "Fleiss' Kappa - Stance": fleiss_stance,
    "Fleiss' Kappa - Irony": fleiss_irony,
    "Fleiss' Kappa High Profile - Hate Speech": fleiss_hs_high,
    "Fleiss' Kappa High Profile - Stance": fleiss_stance_high,
    "Fleiss' Kappa High Profile - Irony": fleiss_irony_high,
    "Fleiss' Kappa Low Profile - Hate Speech": fleiss_hs_low,
    "Fleiss' Kappa Low Profile - Stance": fleiss_stance_low,
    "Fleiss' Kappa Low Profile - Irony": fleiss_irony_low,
}

for key, value in results.items():
    print(f"{key}: {value:.4f}")

import pandas as pd
import matplotlib.pyplot as plt

# Caricamento del dataset
file_path = "/content/sample_data/Azalea-annotations_2025-02-11 (1).csv"
try:
    df = pd.read_csv(file_path)
except FileNotFoundError:
    print(f"Errore: Il file '{file_path}' non è stato trovato. Assicurati di caricarlo correttamente.")
    df = None

if df is not None:
    # Mappatura delle categorie
    mapping_hs = {'yes': 1, 'no': 0}
    mapping_irony = {'yes': 1, 'no': 0}
    mapping_stance = {'favor': 2, 'none': 1, 'against': 0}

    df['hs'] = df['hs'].map(mapping_hs)
    df['irony'] = df['irony'].map(mapping_irony)
    df['stance'] = df['stance'].map(mapping_stance)

    # Creazione della tabella pivot con le annotazioni dei profili high e low
    pivot = df.pivot_table(index='tweet_id', columns='profile', aggfunc='first')

    # Funzione per calcolare la percentuale di accordo
    def agreement_percentage(column):
        agreement = (pivot[(column, 'high')] == pivot[(column, 'low')]).sum()
        total = len(pivot)
        return (agreement / total) * 100

    # Calcolo delle percentuali di accordo
    agreement_hs = agreement_percentage('hs')
    agreement_stance = agreement_percentage('stance')
    agreement_irony = agreement_percentage('irony')

    # Calcolo della percentuale di disaccordo
    disagreement_hs = 100 - agreement_hs
    disagreement_stance = 100 - agreement_stance
    disagreement_irony = 100 - agreement_irony

    # Creazione del grafico delle percentuali di disaccordo
    plt.figure(figsize=(8, 5))
    plt.bar(['Hate Speech', 'Stance', 'Irony'],
            [disagreement_hs, disagreement_stance, disagreement_irony],
            color=['red', 'purple', 'green'])
    plt.ylim(0, 100)
    plt.title("Percentuale di Disaccordo tra Annotatori")
    plt.ylabel("Percentuale (%)")
    plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.stats.inter_rater import fleiss_kappa

# Caricamento del dataset
file_path = "/content/sample_data/Azalea-annotations_2025-02-11 (1).csv"
df = pd.read_csv(file_path)

# Mappatura delle categorie
mapping_hs = {'yes': 1, 'no': 0}
mapping_irony = {'yes': 1, 'no': 0}
mapping_stance = {'favor': 2, 'none': 1, 'against': 0}

df['hs'] = df['hs'].map(mapping_hs)
df['irony'] = df['irony'].map(mapping_irony)
df['stance'] = df['stance'].map(mapping_stance)

# Separazione in base all'uso dei social
df_social = df[df['profile'] == 'high']  # Trio che usa i social
df_no_social = df[df['profile'] == 'low']  # Coppia che non usa i social

# Funzione per creare la matrice per Fleiss' Kappa
def create_fleiss_matrix(data, column, n_categories=3):
    grouped = data.groupby('tweet_id')[column].apply(
        lambda x: np.bincount(x.dropna().astype(int), minlength=n_categories)
    )
    return np.vstack(grouped.values)

# Creazione delle matrici per Fleiss' Kappa nei due gruppi
matrix_hs_social = create_fleiss_matrix(df_social, 'hs', n_categories=3)
matrix_hs_no_social = create_fleiss_matrix(df_no_social, 'hs', n_categories=3)

matrix_stance_social = create_fleiss_matrix(df_social, 'stance', n_categories=3)
matrix_stance_no_social = create_fleiss_matrix(df_no_social, 'stance', n_categories=3)

matrix_irony_social = create_fleiss_matrix(df_social, 'irony', n_categories=3)
matrix_irony_no_social = create_fleiss_matrix(df_no_social, 'irony', n_categories=3)

# Calcolo di Fleiss' Kappa per ciascun gruppo e categoria
fleiss_hs_social = fleiss_kappa(matrix_hs_social)
fleiss_hs_no_social = fleiss_kappa(matrix_hs_no_social)

fleiss_stance_social = fleiss_kappa(matrix_stance_social)
fleiss_stance_no_social = fleiss_kappa(matrix_stance_no_social)

fleiss_irony_social = fleiss_kappa(matrix_irony_social)
fleiss_irony_no_social = fleiss_kappa(matrix_irony_no_social)

# Creazione del grafico di confronto
labels = ['Hate Speech', 'Stance', 'Irony']
values_social = [fleiss_hs_social, fleiss_stance_social, fleiss_irony_social]
values_no_social = [fleiss_hs_no_social, fleiss_stance_no_social, fleiss_irony_no_social]

x = np.arange(len(labels))  # Posizione delle etichette
width = 0.35  # Larghezza delle barre

fig, ax = plt.subplots(figsize=(10, 6))
rects1 = ax.bar(x - width/2, values_social, width, label='Non usa Social', color='blue')
rects2 = ax.bar(x + width/2, values_no_social, width, label='Usa Social', color='red')

# Etichette e titoli
ax.set_ylabel('Fleiss\' Kappa')
ax.set_title('Confronto Accordo tra Chi Usa e Chi Non Usa i Social')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend()

# Mostra il grafico
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Caricamento del dataset
file_path = "/content/sample_data/Azalea-annotations_2025-02-11 (1).csv"
df = pd.read_csv(file_path)

# Mappatura delle categorie
mapping_hs = {'yes': 1, 'no': 0}
mapping_irony = {'yes': 1, 'no': 0}
mapping_stance = {'favor': 2, 'none': 1, 'against': 0}  # Escluderemo 'none' nei calcoli

df['hs'] = df['hs'].map(mapping_hs)
df['irony'] = df['irony'].map(mapping_irony)
df['stance'] = df['stance'].map(mapping_stance)

# Controlliamo se la colonna 'profile' ha i valori attesi
print(df['profile'].unique())  # Verifica se esistono 'high' e 'low'

# Creazione di un pivot più semplice per evitare MultiIndex errati
pivot_social = df[df['profile'] == 'high'].set_index('tweet_id')[['stance']]
pivot_no_social = df[df['profile'] == 'low'].set_index('tweet_id')[['stance']]

# Unione dei due dataframe per il confronto
pivot_merged = pivot_social.join(pivot_no_social, lsuffix='_high', rsuffix='_low')

# Funzione per calcolare la percentuale di accordo
def agreement_percentage(pivot_data, column, exclude_value=None):
    if exclude_value is not None:
        valid_data = pivot_data.loc[~((pivot_data[column + '_high'] == exclude_value) |
                                      (pivot_data[column + '_low'] == exclude_value))]
    else:
        valid_data = pivot_data

    agreement = (valid_data[column + '_high'] == valid_data[column + '_low']).sum()
    total = len(valid_data)
    return (agreement / total) * 100 if total > 0 else 0  # Evita divisioni per zero

# Calcolo delle percentuali di accordo con e senza None per stance nei due gruppi
agreement_stance_with_none = agreement_percentage(pivot_merged, 'stance')  # Include 'none'
agreement_stance_without_none = agreement_percentage(pivot_merged, 'stance', exclude_value=1)  # Esclude 'none'

# Creazione del grafico a doppia barra per confrontare i due calcoli
labels = ['Stance - Con None', 'Stance - Senza None']
values = [agreement_stance_with_none, agreement_stance_without_none]

x = np.arange(len(labels))  # Posizione delle etichette
width = 0.35  # Larghezza delle barre

fig, ax = plt.subplots(figsize=(8, 6))
rects = ax.bar(x, values, width, color=['blue', 'red'])

# Etichette e titoli
ax.set_ylabel('Percentuale di Accordo (%)')
ax.set_title('Confronto Accordo su Stance (Con vs Senza None)')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend(['Accordo'])

# Mostra il grafico
plt.show()

import pandas as pd
import numpy as np

# Caricamento del dataset
file_path = "/content/sample_data/Azalea-annotations_2025-02-11 (1).csv"
df = pd.read_csv(file_path)

# Mappatura delle categorie
mapping_hs = {'yes': 1, 'no': 0}
mapping_irony = {'yes': 1, 'no': 0}
mapping_stance = {'favor': 2, 'none': 1, 'against': 0}

df['hs'] = df['hs'].map(mapping_hs)
df['irony'] = df['irony'].map(mapping_irony)
df['stance'] = df['stance'].map(mapping_stance)

# Calcola il numero di annotazioni uniche per ogni tweet_id su ogni categoria
def disagreement_score(group):
    return group.nunique()  # Conta il numero di annotazioni diverse per ogni tweet

disagreement_df = df.groupby('tweet_id').agg({
    'hs': disagreement_score,
    'stance': disagreement_score,
    'irony': disagreement_score,
    'text': 'first'  # Mantiene il testo del tweet
})

# Ordina i tweet in base alla somma del disaccordo sulle tre categorie
disagreement_df['total_disagreement'] = disagreement_df[['hs', 'stance', 'irony']].sum(axis=1)
disagreement_df = disagreement_df.sort_values(by='total_disagreement', ascending=False)

# Seleziona i 5 tweet con più disaccordo
top_disagreements = disagreement_df.head(20)

# Stampa i risultati
print("\nTop 5 Tweet con Maggiore Disaccordo:\n")
for index, row in top_disagreements.iterrows():
    print(f"Tweet ID: {index}")
    print(f"Testo: {row['text']}")
    print(f"Disaccordo HS: {row['hs']} categorie diverse")
    print(f"Disaccordo Stance: {row['stance']} categorie diverse")
    print(f"Disaccordo Irony: {row['irony']} categorie diverse")
    print(f"Disaccordo Totale: {row['total_disagreement']}\n")
    print("-" * 50)

# Filtra i tweet con disaccordo totale maggiore o uguale a 6
high_disagreement_tweets = disagreement_df[disagreement_df['total_disagreement'] >= 6]

# Stampa i risultati
print("\nTweet con Disaccordo Totale >= 6:\n")
for index, row in high_disagreement_tweets.iterrows():
    print(f"Tweet ID: {index}")
    print(f"Testo: {row['text']}")
    print(f"Disaccordo HS: {row['hs']} categorie diverse")
    print(f"Disaccordo Stance: {row['stance']} categorie diverse")
    print(f"Disaccordo Irony: {row['irony']} categorie diverse")
    print(f"Disaccordo Totale: {row['total_disagreement']}\n")
    print("-" * 50)

import pandas as pd

# Caricamento del dataset (modifica il percorso se necessario)
file_path = "/content/sample_data/Azalea-annotations_2025-02-11 (1).csv"
df = pd.read_csv(file_path)

# Mappatura delle categorie
mapping_hs = {'yes': 1, 'no': 0}
mapping_irony = {'yes': 1, 'no': 0}
mapping_stance = {'favor': 2, 'none': 1, 'against': 0}

df['hs'] = df['hs'].map(mapping_hs)
df['irony'] = df['irony'].map(mapping_irony)
df['stance'] = df['stance'].map(mapping_stance)

# Funzione per calcolare la modalità (etichetta maggioritaria)
def majority_vote(series):
    return series.mode().iloc[0]

# Creazione del dataset con etichetta a maggioranza
majority_df = df.groupby('tweet_id').agg({
    'hs': majority_vote,
    'stance': majority_vote,
    'irony': majority_vote,
    'text': 'first'  # Mantiene il testo del tweet originale
}).reset_index()

# Salva il dataset aggregato in un nuovo file CSV
majority_df.to_csv("dataset_per_BERT.csv", index=False)

# Stampa un'anteprima
print("Dataset con etichetta a maggioranza creato con successo!")
print(majority_df.head())

import pandas as pd

# Caricamento del dataset originale (modifica il percorso se necessario)
file_path = "/content/sample_data/dataset_per_BERT.csv"  # Se sei in Colab, assicurati di caricare il file
df = pd.read_csv(file_path)

# Dizionario con le etichette manuali fornite
manual_updates = {
    "_1006186694461349888": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1443575641752834052": {'hs': 0, 'stance': 2, 'irony': 1},
    "_1175664318240743425": {'hs': 1, 'stance': 0, 'irony': 0},
    "_1463183690524246036": {'hs': 0, 'stance': 2, 'irony': 0},
    "_1461811671433990146": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1452713413721853960": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1117736088393650177": {'hs': 0, 'stance': 0, 'irony': 0},
    "_1125117688085393408": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1147158616413265920": {'hs': 0, 'stance': 0, 'irony': 1},
    "_1152993607143559168": {'hs': 0, 'stance': 2, 'irony': 0},
    "_1173157937675669505": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1173255086291791872": {'hs': 1, 'stance': 0, 'irony': 0},
    "_1190709313561595904": {'hs': 0, 'stance': 0, 'irony': 0},
    "_1401442691892891650": {'hs': 0, 'stance': 2, 'irony': 0},
    "_1441237177866752000": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1440633786576740365": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1374864829379444737": {'hs': 1, 'stance': 0, 'irony': 0},
    "_1430147575936700442": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1429944142067556354": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1242186370279505921": {'hs': 0, 'stance': 0, 'irony': 0},
    "_1359056600485548033": {'hs': 0, 'stance': 1, 'irony': 1},
    "_1361755092760854534": {'hs': 1, 'stance': 0, 'irony': 0},
    "_1421828769963249667": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1464258583982444546": {'hs': 0, 'stance': 0, 'irony': 0},
    "_1151781756623818752": {'hs': 0, 'stance': 2, 'irony': 0},
    "_1397262199404601347": {'hs': 0, 'stance': 0, 'irony': 0},
    "_1061007747653795841": {'hs': 0, 'stance': 1, 'irony': 0},
    "_1476187266284408832": {'hs': 0, 'stance': 0, 'irony': 0},
    "_1040657524700143616": {'hs': 0, 'stance': 2, 'irony': 0},
    "_1009477123751505923": {'hs': 0, 'stance': 2, 'irony': 0},
}

# Applicazione degli aggiornamenti manuali al dataset
for tweet_id, labels in manual_updates.items():
    df.loc[df['tweet_id'] == tweet_id, ['hs', 'stance', 'irony']] = labels['hs'], labels['stance'], labels['irony']

# Salva il dataset aggiornato
df.to_csv("dataset_per_BERT_sistemato.csv", index=False)
print("Dataset aggiornato salvato con successo!")
# Scarica il file aggiornato in Google Colab
from google.colab import files
files.download("dataset_per_BERT_sistemato.csv")